Repository codestates-seb/seb45_main_026, pull requests merged in 2023-09, with the labels that each got.

#133 [FE] 강의 문제 페이지 목업
  client/src/App.js
  client/src/components/UploadPage/Modal/UploadModal.js
  client/src/components/UploadPage/Question.js
  client/src/pages/contents/DetailPage/DetailVideo.js
  client/src/pages/contents/ProblemPage.js
  client/src/pages/contents/UploadPage.js
Labels: Bare Minimum

#135 [FE] 로그인 성공 / 실패 로직 추가, input react-hook-form 리팩토링
  client/src/App.js
  client/src/assets/images/icons/profile/profileGray.svg
  client/src/atoms/inputs/Inputs.js
  client/src/atoms/inputs/Inputs.stories.js
  client/src/components/SignupPageItems/SignupForm.js
  client/src/components/SignupPageItems/SignupForm.style.js
  client/src/components/SignupPageItems/SignupInput.js
  client/src/components/headers/Header.js
  client/src/components/headers/Header.style.js
  client/src/components/headers/HeaderLogo.js
  client/src/components/headers/HeaderLogo.style.js
  client/src/components/headers/HeaderProfile.js
  client/src/components/headers/HeaderProfile.style.js
  client/src/components/loginPageItems/Login.js
  client/src/components/loginPageItems/LoginForm.js
  client/src/components/loginPageItems/SNSLogin.js
  client/src/components/mainPageItems/MainPageItems.js
  client/src/hooks/useConfirm.js
  client/src/pages/contents/MainPage.js
  client/src/redux/createSlice/LoginInfoSlice.js
  client/src/services/authServices.js
  client/src/services/index.js
  client/src/services/userInfoService.js
Labels: Bare Minimum

#140 [FE] 로그인/회원가입/비밀번호찾기/사용자인증
  client/src/App.js
  client/src/atoms/buttons/Buttons.stories.js
  client/src/atoms/buttons/Checkbox.js
  client/src/atoms/buttons/Checkbox.stories.js
  client/src/atoms/inputs/TextAreas.js
  client/src/components/SignupPageItems/SignupForm.js
  client/src/components/SignupPageItems/SignupInput.js
  client/src/components/loginPageItems/ExtraButton.js
  client/src/components/loginPageItems/LoginForm.js
  client/src/components/loginPageItems/LoginForm.style.js
  client/src/components/loginPageItems/LoginInputs.js
  client/src/hooks/useConfirm.js
  client/src/pages/auth/FindPasswordPage.js
  client/src/services/userInfoService.js
Labels: Bare Minimum

#141 [Fe] 강의 상세 페이지 서버 데이터 불러오기
  client/src/App.js
  client/src/pages/contents/DetailPage/DetailPage.js
  client/src/pages/contents/ProblemPage.js
  client/src/redux/Store.js
  client/src/redux/createSlice/VideoInfoSlice.js
Labels: Bare Minimum

#185 [FE] 비디오 출력
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/CartPage/CartItem.js
  client/src/components/CartPage/CartPayInfo.js
  client/src/components/headers/Header.js
  client/src/pages/auth/LoginPage.js
  client/src/pages/contents/CartPage/CartLeft.js
  client/src/pages/contents/CartPage/CartPage.js
  client/src/pages/contents/DetailPage/DetailContent.js
  client/src/pages/contents/DetailPage/DetailPage.js
  client/src/pages/contents/DetailPage/DetailVideo.js
  client/src/pages/contents/LectureListPage.js
  client/src/pages/contents/MainPage.js
  client/src/pages/contents/ProblemPage.js
  client/src/redux/Store.js
  client/src/redux/createSlice/CartsSlice.js
  client/src/redux/createSlice/UISettingSlice.js
  client/src/redux/createSlice/VideoInfoSlice.js
Labels: Bare Minimum

#215 [FE] 내 프로필 기능 구현
  client/src/App.js
  client/src/atoms/buttons/Checkbox.js
  client/src/atoms/inputs/Inputs.js
  client/src/atoms/inputs/Inputs.stories.js
  client/src/components/contentListItems/ChannelNav.js
  client/src/components/contentListItems/Setting.js
  client/src/components/contentListItems/Setting.style.js
  client/src/components/loginPageItems/SNSLogin.js
  client/src/components/sideBar/SideBar.js
  client/src/pages/contents/ChannelPage.js
  client/src/redux/createSlice/LoginInfoSlice.js
  client/src/services/userInfoService.js
Labels: Bare Minimum

#245 [FE] Modal 컴포넌트 구현, 프로필 등록 컴포넌트 구현 중
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/atoms/inputs/ImageInput.js
  client/src/atoms/inputs/Inputs.js
  client/src/atoms/inputs/Inputs.stories.js
  client/src/atoms/modal/ConfirmModal.stories.js
  client/src/atoms/modal/Modal.js
  client/src/atoms/modal/Modal.stories.js
  client/src/components/contentListItems/Setting.js
  client/src/components/findPasswordPageItems/FindPasswordPageForm.js
  client/src/pages/contents/ChannelPage.js
  client/src/redux/createSlice/UISettingSlice.js
  client/src/services/authServices.js
  client/src/services/userInfoService.js
  client/src/styles/tokens.json
Labels: Bare Minimum

#246 [FE] 장바구니 페이지 기본 기능 구현
  client/src/components/CartPage/CartEmpty.js
  client/src/components/CartPage/CartItem.js
  client/src/components/CartPage/CartMyInfo.js
  client/src/components/CartPage/CartPayInfo.js
  client/src/components/DetailPage/ReviewStar.js
  client/src/components/UploadPage/Course.js
  client/src/components/UploadPage/CourseUpload.js
  client/src/components/UploadPage/QuestionUpload.js
  client/src/index.css
  client/src/pages/contents/CartPage/CartLeft.js
  client/src/pages/contents/CartPage/CartPage.js
  client/src/pages/contents/CartPage/CartRight.js
  client/src/pages/contents/UploadPage.js
Labels: Bare Minimum

#256 [FE] authorization 토큰이 만료되면 refresh로 토큰 재발급받도록 기능 추가 #223
  client/src/App.js
  client/src/services/authServices.js
  client/src/services/userInfoService.js
Labels: Bare Minimum

#257 [FE] 모달창 다크모드 적용되도록 수정#222
  client/src/atoms/modal/Modal.js
Labels: Advanced Challenge

#288 [FE] 프로필 이미지 등록 문제 두가지 버그 수정
  client/src/atoms/inputs/ImageInput.js
  client/src/atoms/modal/Modal.js
  client/src/redux/Store.js
Labels: bug

#291 [FE] 강의 문제 업로드 기능 구현
  client/src/App.js
  client/src/components/CartPage/ProblemPage/ProblemBox.js
  client/src/components/CartPage/ProblemPage/ProblemType.js
  client/src/components/CartPage/ProblemPage/SelectNum.js
  client/src/components/UploadPage/CourseUpload.js
  client/src/components/UploadPage/Modal/UploadModal.js
  client/src/components/UploadPage/ProblemUpload.js
  client/src/pages/contents/DetailPage/DetailPage.js
  client/src/pages/contents/DetailPage/DetailVideo.js
  client/src/pages/contents/ProblemPage.js
  client/src/redux/Store.js
  client/src/redux/createSlice/ProblemSlice.js
Labels: Bare Minimum, Advanced Challenge

#294 [FE] 강의 업로드 로직 수정
  client/src/components/UploadPage/CourseUpload.js
Labels: Bare Minimum

#360 [FE] 리뷰 CRUD 기능 완료
  client/src/App.js
  client/src/assets/images/icons/star/star_lefthalf.svg
  client/src/assets/images/icons/star/star_righthalf.svg
  client/src/atoms/loading/Loading.js
  client/src/components/CartPage/CartPayInfo.js
  client/src/components/DetailPage/Pagination.js
  client/src/components/DetailPage/ReviewList.js
  client/src/components/DetailPage/ReviewStar.js
  client/src/components/DetailPage/SubscribeBtn.js
  client/src/components/ProblemPage/ProblemBox.js
  client/src/components/UploadPage/CourseUpload.js
  client/src/components/UploadPage/ProblemUpload.js
  client/src/components/contentListItems/Stars.js
  client/src/pages/contents/CartPage/TossPayment.js
  client/src/pages/contents/DetailPage/DetailContent.js
  client/src/pages/contents/DetailPage/DetailPage.js
  client/src/pages/contents/DetailPage/DetailReview.js
  client/src/pages/contents/DetailPage/DetailVideo.js
  client/src/redux/createSlice/UISettingSlice.js
Labels: Bare Minimum

#378 [FE]시청한 강의 목록 구현
  client/src/App.js
  client/src/components/contentListItems/HorizonItem.js
  client/src/components/contentListItems/VerticalItem.js
  client/src/components/filters/CategoryFilter.js
  client/src/components/filters/FilterDropdown.js
  client/src/pages/contents/ChannelListPage.js
  client/src/pages/contents/ChannelPage.js
  client/src/pages/contents/WatchedListPage.js
  client/src/redux/createSlice/FilterSlice.js
Labels: Bare Minimum

#381 [FE] 강의 상세페이지 (장바구니 및 구매하기 설정)
  client/src/App.js
  client/src/components/DetailPage/Pagination.js
  client/src/components/DetailPage/ReviewList.js
  client/src/components/DetailPage/ReviewStar.js
  client/src/components/DetailPage/SubscribeBtn.js
  client/src/components/ProblemPage/ProblemBox.js
  client/src/components/UploadPage/Modal/UploadModal.js
  client/src/pages/contents/DetailPage/DetailContent.js
  client/src/pages/contents/DetailPage/DetailPage.js
  client/src/pages/contents/DetailPage/DetailReview.js
  client/src/pages/contents/DetailPage/DetailVideo.js
  client/src/redux/createSlice/VideoInfoSlice.js
Labels: Bare Minimum

#398 [FE] 비디오 커스텀 컨트롤러 완성
  client/package-lock.json
  client/package.json
  client/src/assets/images/icons/FullScreen.svg
  client/src/assets/images/icons/Pause.svg
  client/src/assets/images/icons/Play.svg
  client/src/assets/images/icons/Volume.svg
  client/src/assets/images/icons/listItem/Basket.svg
  client/src/assets/images/icons/listItem/Cart.svg
  client/src/components/DetailPage/AddCart.js
  client/src/components/DetailPage/Pagination.js
  client/src/components/DetailPage/SubscribeBtn.js
  client/src/components/DetailPage/VideoPlayer.js
  client/src/components/contentListItems/HorizonItem.js
  client/src/pages/contents/DetailPage/DetailReview.js
  client/src/pages/contents/DetailPage/DetailVideo.js
  client/src/pages/contents/LectureListPage.js
Labels: Bare Minimum, Advanced Challenge

#411 [FE]검색결과창 및 검색창 구현
  client/src/App.js
  client/src/assets/images/icons/search/searchGray.svg
  client/src/assets/images/icons/search/searchLightGray.svg
  client/src/components/channelListItems/ChannelListItem.js
  client/src/components/contentListItems/ChannelHome.js
  client/src/components/contentListItems/ChannelItem.js
  client/src/components/contentListItems/ChannelList.js
  client/src/components/contentListItems/ChannelNotice.js
  client/src/components/contentListItems/ListToggle.js
  client/src/components/contentListItems/NoticeItem.js
  client/src/components/contentListItems/Searchsubmit.js
  client/src/components/filters/CategoryFilter.js
  client/src/components/searchDropdown/SearchChannel.js
  client/src/components/searchDropdown/SearchDropdown.js
  client/src/components/searchDropdown/SearchLecture.js
  client/src/pages/contents/ChannelListPage.js
  client/src/pages/contents/ChannelPage.js
  client/src/pages/contents/LectureListPage.js
  client/src/pages/contents/PurchasedListPage.js
  client/src/pages/contents/ResultPage.js
  client/src/pages/contents/SubscribedListPage.js
Labels: Bare Minimum

#421 [FE] Advanced 기능 추가
  client/src/atoms/buttons/ListToggle.js
  client/src/atoms/buttons/Toggle.js
  client/src/atoms/layouts/PageContainer.js
  client/src/components/CartPage/CartItem.js
  client/src/components/DetailPage/VideoPlayer.js
  client/src/components/UploadPage/CourseUpload.js
  client/src/components/UploadPage/Modal/SelectToggle.js
  client/src/components/UploadPage/Modal/UploadModal.js
  client/src/components/UploadPage/ProblemUpload.js
  client/src/components/contentListItems/ChannelList.js
  client/src/components/contentListItems/HorizonItem.js
  client/src/components/headers/Header.js
  client/src/components/headers/HeaderLogo.js
  client/src/components/headers/HeaderProfile.js
  client/src/pages/contents/CartPage/CartPage.js
  client/src/pages/contents/ChannelPage.js
  client/src/pages/contents/DetailPage/DetailVideo.js
Labels: Bare Minimum, Advanced Challenge

#446 [FE] alert, confirm 커스텀 모달창 리팩토링
  client/src/atoms/buttons/ListToggle.js
  client/src/atoms/modal/Modal.js
  client/src/components/CartPage/CartPayInfo.js
  client/src/components/DetailPage/AddCart.js
  client/src/components/DetailPage/ReviewList.js
  client/src/components/DetailPage/VideoPlayer.js
  client/src/components/UploadPage/CourseUpload.js
  client/src/components/UploadPage/Modal/UploadModal.js
  client/src/components/UploadPage/ProblemUpload.js
  client/src/pages/contents/CartPage/CartPage.js
  client/src/pages/contents/CartPage/TossPayment.js
  client/src/pages/contents/DetailPage/DetailReview.js
  client/src/pages/contents/DetailPage/DetailVideo.js
Labels: Bare Minimum

#461 [FE] 에러 로직 처리
  client/src/App.js
  client/src/components/UploadPage/CourseUpload.js
  client/src/pages/NotFound.js
  client/src/pages/contents/CartPage/CartLeft.js
  client/src/pages/contents/ProblemPage.js
Labels: Bare Minimum

#493 [FE] 비디오 컨트롤러 현재 시간 및 음소거 기능 및 시간이동 기능 추가
  client/src/assets/images/icons/Mute.svg
  client/src/assets/images/icons/Prev.svg
  client/src/assets/images/icons/PrevBtn.svg
  client/src/components/DetailPage/VideoPlayer.js
  client/src/pages/contents/DetailPage/DetailPage.js
  client/src/pages/contents/DetailPage/DetailVideo.js
Labels: Advanced Challenge
